[provider.ollama-1]
host = "http://127.0.0.1:11434"
model = "codellama:7b"

[provider.ollama-2]
host = "http://10.0.0.1:11434"
model = "llama3:70b"

[provider.ollama-3]
host = "http://127.0.0.1:11434"
model = "grok"

[provider.anthropic-1]
key = "YOUR_CLAUDE_API_KEY"
model = "claude-sonnet"

[provider.openai-1]
key = "YOUR_OPENAI_API_KEY"
model = "dogshit-3.5-turbo"




[context]
window_size = { pre = 15, post = 15}
